app:
  name: "TestApp"
  version: "1.0.0" 
  debug: true

database:
  host: "localhost"
  port: 5432
  credentials:
    username: "admin"
    password: "secret"

features:
  feature1: true
  feature2: false

numbers:
  int_value: 42
  float_value: 3.14

simple_list: "item1,item2,item3"
